### ISSUE TITLE
How long does it take to download rgb_frames?

### ISSUE THREAD

**Issue by gongda0e** [epic-kitchens/epic-kitchens-100-annotations#10]
Hello,

Thank you for your effort to the dataset. I started to download epic-kitchen 55 two days ago. However, it is still downloading people 04. I wonder how long does it take to download rbg_frames of Epic-kitcens 55?

**Comment by dmoltisanti** [comment]
Hello, thanks for your interest in our dataset! Depending on the region you live in, data downloading may be slow. 

For these cases we recommend using Torrent. You can find [EPIC-KITCHENS-55 here](https://academictorrents.com/details/d08f4591d1865bbe3436d1eb25ed55aae8b8f043) and [EPIC-KITCHENS-100 here](https://academictorrents.com/details/cc2d9afabcbbe33686d2ecd9844b534e3a899f4b).

Hope this help, closing the issue :)
