### ISSUE TITLE
Any plans for an epic-kitchens-100-lib python package

### ISSUE THREAD

**Issue by escorciav** [epic-kitchens/epic-kitchens-100-annotations#12]
Dear team,

I'm wondering if you are planning to:
- develop & release an epic-kitchens-100-lib python package
- upgrade the [epic-kitchens-55-lib](https://github.com/epic-kitchens/epic-kitchens-55-lib) to deal with the epic-100 data
?

Cheers,
Victor

**Comment by willprice** [comment]
No, there aren't any plans for this. I developed this in my free time and no longer have enough to do so.
