### ISSUE TITLE
An equivalent epic-descriptions.csv file

### ISSUE THREAD

**Issue by nikky4D** [epic-kitchens/epic-kitchens-100-annotations#15]
In Epic55, there is an EPIC_descriptions.csv file describing the general actions happening in the video. Is there a similar file for Epic100?

**Comment by dimadamen** [comment]
No. We have not collected this information as we didn't find it generally helpful or representative of the variety of activities taking place in the video.

**Comment by nikky4D** [comment]
Thank you
