### ISSUE TITLE
Frame 35804 (P01) matches with two rows in the annotation

### ISSUE THREAD

**Issue by anjugopinath** [epic-kitchens/epic-kitchens-100-annotations#17]
Hi,

This is frame with id frame_0000035804.jog (P01).

![image](https://user-images.githubusercontent.com/4654298/132083483-f34c2a7f-24de-4d18-b178-55d0534c3435.png)

I found two rows with where the frame number falls within the range of starting and ending frame number.
https://raw.githubusercontent.com/epic-kitchens/epic-kitchens-100-annotations/master/EPIC_100_train.csv

![image](https://user-images.githubusercontent.com/4654298/132083515-f1a3ede4-a6ec-4c02-b814-3e949edd9aa4.png)

Since frame name is frame_0000035804.jpg, the I searched for frame number 35804.

**Comment by EGO4D** [comment]
I am not sure I understand your question. The two lines you highlighted are in two different videos. The first one is froomo video P01_01 and the second is from video P01_109. These are two different videos altogether.
The frame number is only unique within thee video. You need the video filename to identify which frame it is.

**Comment by dimadamen** [comment]
I am not sure I understand your question. The two lines you highlight come from two different videos.
The first one is from video P01_01. The second is from video P01_109. These are unique and different videos.
The frame number is relative to a video, not globally within the dataset.

**Comment by anjugopinath** [comment]
Got it. Sorry for the confusion.
Thank You!
