### ISSUE TITLE
The download dataset is different from the pkl file.

### ISSUE THREAD

**Issue by realgump** [epic-kitchens/epic-kitchens-100-annotations#18]
I have download the dataset from [https://data.bris.ac.uk/datasets/3h91syskeag572hl6tvuovwv4d](https://data.bris.ac.uk/datasets/3h91syskeag572hl6tvuovwv4d)  and [https://data.bris.ac.uk/datasets/2g1n6qdydwa9u22shpxqzp0t8m](https://data.bris.ac.uk/datasets/2g1n6qdydwa9u22shpxqzp0t8m), and find that the number of videos in my download dataset is different from the pkl file. 
There are 702 videos in download dataset, and P06_04, P06_06 is not in the pkl file. In addition, I find some videos for training in pkl is in the test folder of _3h91syskeag572hl6tvuovwv4d_ . 
Could you please tell if I make some mistake?

**Comment by dimadamen** [comment]
We missed this issue. Some of the videos you note are part of the **test** set and thus they won't be in the released annotations obviously.
