### ISSUE TITLE
how to process the rgb frame (.tar)

### ISSUE THREAD

**Issue by linqinghong** [epic-kitchens/epic-kitchens-100-annotations#19]
hi, i have downloaded all the rgb frames of epic-kitchens 100, which are organized as .tar files.
i want to extract all of them and use the figure to train my model.

1) Do you provide **decompression commands** and corresponding **dataloader**?

2) In addition, how many fps are used in these frames extraction, will the performance of the frame input be worse than the raw video as input?

thanks!

**Comment by dimadamen** [comment]
1. There isn't a specific decompression command. This is standard .tar. Not sure what you mean by "corresponding data loader". If you mean loading data for action recognition tasks, then you should check our repo: 
This contains code and models for 5 action recognition tasks. For other tasks, please check the corresponding starting code from our website (one per challenge)
2. Please look at our paper and README on the fps for various videos and how these are extracted. 
No single model can take raw video as input, so comparing frames to video is not a valid question to ask. 
We kindly request that you check all valid resources we provide on our GitHub and webpage before raising questions.

**Comment by linqinghong** [comment]
Thank for your replay, i will carefully check the resources you provided.
