### ISSUE TITLE
Where can I get the the test accuracy of action recognition benchmark?

### ISSUE THREAD

**Issue by Hou9612** [epic-kitchens/epic-kitchens-100-annotations#20]
Thanks for this wonderful work!  I can't find the ground truth file of test dataset in this repository. Do I need to take part in this challenge [(EPIC-KITCHENS-100 Action Recognition)](https://codalab.lisn.upsaclay.fr/competitions/776#learn_the_details) if I want to get the test accuracy of my model?

**Comment by dmoltisanti** [comment]
Hi, yes that's right, the test test is private and you'll need to submit your predictions to evaluate your model.

**Comment by Hou9612** [comment]
@dmoltisanti Hello, I have a new question, How can I get the test accuracy affer the competition ends?  (just for getting the test accuracy of my model).

**Comment by dimadamen** [comment]
The server will open again in July after CVPR. This is an open testing phase that extends until Dec 2022. We then move to a challenge phase from Jan 2023. The server is open throughout the year for evaluating on the test set, an only closed temporarily in June to decide on the winners.
