### ISSUE TITLE
towel vs towel:kitchen (noun classes)

### ISSUE THREAD

**Issue by iranroman** [epic-kitchens/epic-kitchens-100-annotations#23]
should towel and towel:kitchen be the same noun?

Right now they are treated as different in the file `EPIC_100_noun_classes.csv`

**Comment by dimadamen** [comment]
Kitchen towel is another name for the roll paper (https://en.wikipedia.org/wiki/Paper_towel) and is thus very different from a standard towel, hence the class distinction.
Yes, they are different classes indeed.
