### ISSUE TITLE
How can I apply the gyro and accl in meta_data to construct the transformation matrix of the camera?

### ISSUE THREAD

**Issue by Hoyyyaard** [epic-kitchens/epic-kitchens-100-annotations#32]

**Comment by dimadamen** [comment]
I am not sure I understand your question. What is the "transformation matrix of the camera"? 
We publish meta data containing accelerometer and gyroscope data. These have been collected using the public [GoPro-utilities repo](https://github.com/JuanIrache/gopro-utils). Please refer to that repo for the formats of the released meta_data files.

**Comment by Hoyyyaard** [comment]
Thanks for your reply.  Can you share the gps meta data when you collect when you collect the video?  Current meta data only contains accl and gyro data.

**Comment by dimadamen** [comment]
As we detailed here: https://data.bris.ac.uk/datasets/2g1n6qdydwa9u22shpxqzp0t8m/readme.txt
that GPS information is suppressed for anonymity and were not recorded.
