### ISSUE TITLE
Videos in Epic_100_train.csv not included in video directory.

### ISSUE THREAD

**Issue by dfan** [epic-kitchens/epic-kitchens-100-annotations#35]
Some videos listed in the train annotation are not in the video directory. For instance, P11 is listed in EPIC_100_train.csv
```
P11_01_0,P11,P11_01,00:00:04.490,00:00:03.60,00:00:05.66,216,339,open door,open,3,door,3,['door'],[3]
```

But the P11 video folder is not provided in the videos/train directory. It is provided in videos/test directory. https://academictorrents.com/details/d08f4591d1865bbe3436d1eb25ed55aae8b8f043

Is there a reason for this?

**Comment by dimadamen** [comment]
The train/test splits changed between the 2018 release (which is the directory you're listing here) and the 2020 release (which is the EPIC_100_train file you're referring to). 
We got rid of the previous test set, and re-organised the videos with the previous test set videos being moved into either train or val, creating a new test set, with new videos.
The folder structure though was static. Our script allows you to re-structure the folders if you use it. 
Hope this answers your Q,

**Comment by dfan** [comment]
Thank you! The extension torrent does not group video by train/val/test set
as the root folder is the video ID. Does this mean the extension download
is purely for the test set?

**Comment by dimadamen** [comment]
No... the extension torrent only has the *new* videos, which includes training + val + test. 
I meant that if you use our download script here: https://github.com/epic-kitchens/epic-kitchens-download-scripts it would restructure your files into the right folder.

**Comment by dimadamen** [comment]
If you've already downloaded all videos, your easiest solution is just to put ALL VIDEOS into one folder, and rely on the .csv files to do the separation. This would be my suggestion.
Hope this answers your question.

**Comment by dfan** [comment]
Thank you that makes sense now. It would be great to clarify the full download steps on the website. I used the torrent because the download script was a few orders of magnitude slower.
