### ISSUE TITLE
Missing narrations in EPIC_100_test_timestamps.csv

### ISSUE THREAD

**Issue by yujiangpu20** [epic-kitchens/epic-kitchens-100-annotations#37]
Hi, I noticed that only train and validation csv file provide narrations while it is missing in the test annotation file, how can it be used for the evaluation of action recognition or detection task?

**Comment by dimadamen** [comment]
Correct. The test narrations are part of the action recognition and action detection task ground truth so they are hidden behind the Codalab server and cannot be released. The start-end times have been released to assist with the recognition task but they should not be used for the detection task.

**Comment by yujiangpu20** [comment]
Got it. Thanks!
