### ISSUE TITLE
The durations of frames and metadata(gyro and accl) are different

### ISSUE THREAD

**Issue by dy1998** [epic-kitchens/epic-kitchens-100-annotations#39]
Hello, I found some videos with metadata has the duration different problems. 
For example, for video 'P01_103', it has 8905 frames with 50 fps. The duration of this video is 8905/50 = 178.1s. The final row of 'gyro' is 174994.95 ms, which can be convert to 174.99s. There is a 3-second interval between these two durations. The duration  from 'EPIC_100_video_info.csv' is 178.02s. I want to know if these 3 seconds were not recorded at the end of the video. 

PS：I found similiar problems from the corresponding repo. Perhaps it's related to this.
https://github.com/JuanIrache/gopro-utils/issues/17

**Comment by dimadamen** [comment]
The released gyro are the raw output of the GoPro. Any missing gyro readings are the result of the GoPro not recording these. We didn't explicitly switch on/off any sensory data.

**Comment by dy1998** [comment]
> The released gyro are the raw output of the GoPro. Any missing gyro readings are the result of the GoPro not recording these. We didn't explicitly switch on/off any sensory data.

Ok, thanks for your reply.
