### ISSUE TITLE
Any plans for sharing the features?

### ISSUE THREAD

**Issue by hyf015** [epic-kitchens/epic-kitchens-100-annotations#8]
Hi, thank you for contributing to the datasets! Just want to know is there any plan to share the TSN features mentioned in the paper for reproducing the benchmark results? Thanks.

**Comment by dimadamen** [comment]
We are in the process of releasing the models (not the features). You can use the models to reproduce the results. We hope for that to come out in the next couple of weeks,

**Comment by hyf015** [comment]
Wondering if there are updates on the release of the models?

**Comment by dimadamen** [comment]
Yes, all models have been released a while ago! Please watch the whole set of repos, as this repo is only related to annotations. All action recognition model baselines (including TSN) are now online at:
https://github.com/epic-kitchens/C1-Action-Recognition
