### ISSUE TITLE
Error with the UDA JSON file

### ISSUE THREAD

**Issue by plana93** [epic-kitchens/epic-kitchens-100-annotations#9]
I had some problem with the JSON creation, I tried to submit at UDA challenge using your pkl files (EPIC_100_uda_source_test_timestamps and EPIC_100_uda_target_test_timestamps) and I obtained  two different errors: 

1 ) epic_challenges.domain_adaptation.validation.MissingResultException: The following narration ids are missing: P12_03_2

2 ) epic_challenges.domain_adaptation.validation.UnexpectedResultException: Found the following unexpected narration ids: P12_03_112.

**Comment by dimadamen** [comment]
Thanks for your email. We are investigating the issue. Give us a few days please

**Comment by dimadamen** [comment]
There's certainly an issue with source_test that we need to resolve. Remember that you can submit to the challenge only by using target_test, as source_test is optional. We are looking into fixing source_test, but will take a little while to fix.

**Comment by jonmun** [comment]
We have fixed the issue with source_test. You should now be able to submit to both target_test and source_test with no issues.

Closing the issue as this has now been resolved.
